### ISSUE TITLE
Is Voicebank pre-trained weight available?

### ISSUE THREAD

**Issue by l4zyf9x** [winddori2002/MANNER#2]
Just wonder whether is Voicebank's pre-trained weight available now?

**Comment by winddori2002** [comment]
I will upload the weights soon.
Thank you.

**Comment by ariel-c-verbit** [comment]
Hi!
Thank you very much for sharing this repo publicly.
you stated that the model you uploaded is MANNER (small), but when i tried to load it with the small version i got a mismatch error. I then loaded it with the large MANNER model and got it ok.
I think the weights you gave us are of the large MANNER model. Am I right?

**Comment by winddori2002** [comment]
Hi,

We have uploaded both MANNER (small) and MANNER (base) a while ago.
The weight you tried is MANNER (base) maybe.
You can check the updated release.
Thank you

**Comment by lichengxi1** [comment]
Hi have you uploaded the pretrained weights? I can't find it.
