### ISSUE TITLE
Hardware Requirements For Training

### ISSUE THREAD

**Issue by MrZ13** [winddori2002/MANNER#8]
Hi!
I am planning to train MANNER and MANNER(small) model from sketch, but I don't know whether the gpu resource that I have is enough. Could you please tell me how much memory do the training procedure need？(following the configuration introduced in the paper)

**Comment by winddori2002** [comment]
Hi, 
We used a batch size of 4. 
It requires about 16G and 5G for MANNER and MANNER(small), respectively.
Thank you.

**Comment by MrZ13** [comment]
> 

I see, thank you for your reply!
